// 코스피/코스닥 주요 종목 데이터베이스
export const KR_STOCKS_DB = [
  // 시가총액 상위 + 주요 종목
  { symbol: '005930', name: '삼성전자', market: 'kr' as const },
  { symbol: '000660', name: 'SK하이닉스', market: 'kr' as const },
  { symbol: '035420', name: 'NAVER', market: 'kr' as const },
  { symbol: '005380', name: '현대차', market: 'kr' as const },
  { symbol: '035720', name: '카카오', market: 'kr' as const },
  { symbol: '051910', name: 'LG화학', market: 'kr' as const },
  { symbol: '006400', name: '삼성SDI', market: 'kr' as const },
  { symbol: '207940', name: '삼성바이오로직스', market: 'kr' as const },
  { symbol: '068270', name: '셀트리온', market: 'kr' as const },
  { symbol: '028260', name: '삼성물산', market: 'kr' as const },
  { symbol: '105560', name: 'KB금융', market: 'kr' as const },
  { symbol: '055550', name: '신한지주', market: 'kr' as const },
  { symbol: '012330', name: '현대모비스', market: 'kr' as const },
  { symbol: '096770', name: 'SK이노베이션', market: 'kr' as const },
  { symbol: '017670', name: 'SK텔레콤', market: 'kr' as const },
  { symbol: '034730', name: 'SK', market: 'kr' as const },
  { symbol: '402340', name: 'SK스퀘어', market: 'kr' as const },
  { symbol: '302440', name: 'SK바이오사이언스', market: 'kr' as const },
  { symbol: '018260', name: '삼성에스디에스', market: 'kr' as const },
  { symbol: '066570', name: 'LG전자', market: 'kr' as const },
  { symbol: '003670', name: '포스코퓨처엠', market: 'kr' as const },
  { symbol: '005490', name: 'POSCO홀딩스', market: 'kr' as const },
  { symbol: '000270', name: '기아', market: 'kr' as const },
  { symbol: '009150', name: '삼성전기', market: 'kr' as const },
  { symbol: '011200', name: 'HMM', market: 'kr' as const },
  { symbol: '086790', name: '하나금융지주', market: 'kr' as const },
  { symbol: '032640', name: 'LG유플러스', market: 'kr' as const },
  { symbol: '015760', name: '한국전력', market: 'kr' as const },
  { symbol: '033780', name: 'KT&G', market: 'kr' as const },
  { symbol: '030200', name: 'KT', market: 'kr' as const },
  { symbol: '003550', name: 'LG', market: 'kr' as const },
  { symbol: '010130', name: '고려아연', market: 'kr' as const },
  { symbol: '034220', name: 'LG디스플레이', market: 'kr' as const },
  { symbol: '011070', name: 'LG이노텍', market: 'kr' as const },
  { symbol: '047810', name: '한국항공우주', market: 'kr' as const },
  { symbol: '012450', name: '한화에어로스페이스', market: 'kr' as const },
  { symbol: '018880', name: '한온시스템', market: 'kr' as const },
  { symbol: '036570', name: '엔씨소프트', market: 'kr' as const },
  { symbol: '251270', name: '넷마블', market: 'kr' as const },
  { symbol: '112040', name: '위메이드', market: 'kr' as const },
  { symbol: '259960', name: '크래프톤', market: 'kr' as const },
  { symbol: '095720', name: '웅진씽크빅', market: 'kr' as const },
  { symbol: '004170', name: '신세계', market: 'kr' as const },
  { symbol: '139480', name: '이마트', market: 'kr' as const },
  { symbol: '000120', name: 'CJ대한통운', market: 'kr' as const },
  { symbol: '001040', name: 'CJ', market: 'kr' as const },
  { symbol: '097950', name: 'CJ제일제당', market: 'kr' as const },
  { symbol: '090430', name: '아모레퍼시픽', market: 'kr' as const },
  { symbol: '002790', name: '아모레G', market: 'kr' as const },
  { symbol: '271560', name: '오리온', market: 'kr' as const },
  { symbol: '003490', name: '대한항공', market: 'kr' as const },
  { symbol: '020560', name: '아시아나항공', market: 'kr' as const },
  { symbol: '161390', name: '한국타이어앤테크놀로지', market: 'kr' as const },
  { symbol: '267250', name: '현대중공업지주', market: 'kr' as const },
  { symbol: '009540', name: '한국조선해양', market: 'kr' as const },
  { symbol: '010140', name: '삼성중공업', market: 'kr' as const },
  { symbol: '010620', name: '현대미포조선', market: 'kr' as const },
  { symbol: '000810', name: '삼성화재', market: 'kr' as const },
  { symbol: '024110', name: '기업은행', market: 'kr' as const },
  { symbol: '175330', name: 'JB금융지주', market: 'kr' as const },
  { symbol: '016360', name: 'LS', market: 'kr' as const },
  { symbol: '010120', name: 'LS전선아시아', market: 'kr' as const },
  { symbol: '000720', name: '현대건설', market: 'kr' as const },
  { symbol: '047050', name: '포스코인터내셔널', market: 'kr' as const },
  { symbol: '078930', name: 'GS', market: 'kr' as const },
  { symbol: '011780', name: '금호석유', market: 'kr' as const },
  { symbol: '011170', name: '롯데케미칼', market: 'kr' as const },
  { symbol: '014680', name: '한솔케미칼', market: 'kr' as const },
  { symbol: '373220', name: 'LG에너지솔루션', market: 'kr' as const },
  { symbol: '003410', name: '쌍용C&E', market: 'kr' as const },
];

export const US_STOCKS_DB = [
  { symbol: 'AAPL', name: 'Apple', market: 'us' as const },
  { symbol: 'MSFT', name: 'Microsoft', market: 'us' as const },
  { symbol: 'GOOGL', name: 'Alphabet (Google)', market: 'us' as const },
  { symbol: 'AMZN', name: 'Amazon', market: 'us' as const },
  { symbol: 'NVDA', name: 'NVIDIA', market: 'us' as const },
  { symbol: 'TSLA', name: 'Tesla', market: 'us' as const },
  { symbol: 'META', name: 'Meta (Facebook)', market: 'us' as const },
  { symbol: 'BRK.B', name: 'Berkshire Hathaway', market: 'us' as const },
  { symbol: 'JPM', name: 'JPMorgan Chase', market: 'us' as const },
  { symbol: 'V', name: 'Visa', market: 'us' as const },
  { symbol: 'JNJ', name: 'Johnson & Johnson', market: 'us' as const },
  { symbol: 'WMT', name: 'Walmart', market: 'us' as const },
  { symbol: 'PG', name: 'Procter & Gamble', market: 'us' as const },
  { symbol: 'MA', name: 'Mastercard', market: 'us' as const },
  { symbol: 'UNH', name: 'UnitedHealth', market: 'us' as const },
  { symbol: 'HD', name: 'Home Depot', market: 'us' as const },
  { symbol: 'DIS', name: 'Disney', market: 'us' as const },
  { symbol: 'BAC', name: 'Bank of America', market: 'us' as const },
  { symbol: 'NFLX', name: 'Netflix', market: 'us' as const },
  { symbol: 'ADBE', name: 'Adobe', market: 'us' as const },
  { symbol: 'CRM', name: 'Salesforce', market: 'us' as const },
  { symbol: 'XOM', name: 'ExxonMobil', market: 'us' as const },
  { symbol: 'CVX', name: 'Chevron', market: 'us' as const },
  { symbol: 'PFE', name: 'Pfizer', market: 'us' as const },
  { symbol: 'ABBV', name: 'AbbVie', market: 'us' as const },
  { symbol: 'KO', name: 'Coca-Cola', market: 'us' as const },
  { symbol: 'PEP', name: 'PepsiCo', market: 'us' as const },
  { symbol: 'COST', name: 'Costco', market: 'us' as const },
  { symbol: 'TMO', name: 'Thermo Fisher', market: 'us' as const },
  { symbol: 'MRK', name: 'Merck', market: 'us' as const },
  { symbol: 'INTC', name: 'Intel', market: 'us' as const },
  { symbol: 'AMD', name: 'AMD', market: 'us' as const },
  { symbol: 'QCOM', name: 'Qualcomm', market: 'us' as const },
  { symbol: 'IBM', name: 'IBM', market: 'us' as const },
  { symbol: 'ORCL', name: 'Oracle', market: 'us' as const },
  { symbol: 'CSCO', name: 'Cisco', market: 'us' as const },
  { symbol: 'TXN', name: 'Texas Instruments', market: 'us' as const },
  { symbol: 'AVGO', name: 'Broadcom', market: 'us' as const },
  { symbol: 'NOW', name: 'ServiceNow', market: 'us' as const },
  { symbol: 'PYPL', name: 'PayPal', market: 'us' as const },
];

export const ALL_STOCKS_DB = [...KR_STOCKS_DB, ...US_STOCKS_DB];
